server:
  port: 7000
  
spring:
  application:
    name: Microservice-Gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:
      - id: Supplier-Service
        uri: lb://Supplier-Service
        predicates:
        - Path=/supplier/**
      - id: Drugs-Microservice
        uri: lb://Drugs-Microservice
        predicates:
        - Path=/drugs/**
      - id: Order-Microservice
        uri: lb://Order-Microservice
        predicates:
        - Path=/user/**, /address/**
      - id: Login-Service
        uri: lb://Login-Service
        predicates:
        - Path=/api/auth/**, /api/user-auth/**
        
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
        
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
      
  instance:
    hostname: localhost
         
